[package]
name = "minimg"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "A mini image library"
repository = "https://github.com/ThePJB/minimg"

[dependencies]
minvect = "0.1.6"
png = "0.17.10"
